Revert "add healthcheck in docker."
This reverts commit f44a3d6c1a620d2f76818076c3ac68e879b4d47b.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -70,27 +70,23 @@ jobs:
       - name: Create .env file for Docker Compose
         run: echo "WEB_IMAGE_TAG=${{ steps.image_tag.outputs.tag }}" > .env
 
-      - name: Run the container using Docker Compose
-        run: docker compose up -d
- 
-      - name: Verify Container Health
-        id: health_check
+        # use condition polling to perform a health check 
+      - name: health check
         run: |
-          CONTAINER_NAME=$(docker compose ps -q web)
-          for i in {1..3}
-          do
-            status=$(docker inspect --format '{{.State.Health.Status}}' $CONTAINER_NAME)
-            echo "Attempt $i: Container status is $status"
-            if [ "$status" = "healthy" ]; then
-              echo "Container is healthy!"
-              exit 0
-            fi
-            sleep 2
-          done
-          echo "Container did not become healthy in time"
-          echo "storing logs to docker_log.txt---"
-          docker compose logs web > docker_log.txt
-          exit 1
+            echo "startign health check"
+            for i in {1..3}
+            do
+                response=$(curl -s --fail http://localhost:3000/health) 
+                echo "Response: $response"
+                if [[ $response == *"Still working"* ]] ; then
+                echo "Health check passed on attempt $i "
+                exit 0
+                fi
+                echo "Attempt $i failed. Retrying in 1 seconds..."
+                sleep 1
+            done
+            echo "Health check failed after 3 attempts"
+            exit 1
 
       - name: Upload Docker logs on failure
         if: failure() && steps.health_check.outcome == 'failure'
