update health check

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -66,8 +66,22 @@ jobs:
       - name: Run the container
         run: docker run -d --name test_container -p 3000:3000 ${{ steps.image_tag.outputs.tag }}
 
-      - name: test_app 
-        run: sh test.sh
+        # use condition polling to perform a health check 
+      - name: health check
+        run: |
+            echo "startign health check"
+            for i in {1..3}
+            do
+                if curl -sf http://localhost:3000/health | grep -q "Still working"; then
+                echo "Health check passed on attempt $i "
+                exit 0
+                fi
+                echo "Attempt $i failed. Retrying in 1 seconds..."
+                sleep 1
+            done
+            echo "Health check failed after 3 attempts"
+            exit 1
+
 
       - name: Stop the container
         if: always() # This step runs even if the health check fails
